#开发环境（本地）

#服务
server:
  port: 80  #tomcat端口号
  servlet:
    context-path: /o2o  #项目根路径/应用上下文路径


#Redis
redis:
  host: localhost   #主机IP
  port: 6379        #Redis默认端口号
  database: 0
  #jedis连接池
  pool:
    max-total: 30  #连接池中允许的最大连接数：即能同时建立的‘最大连接个数’，连接全部用完，则需进行等待
    min-idle: 1     #允许池中空闲的最小连接数：低于minIdle时，将创建新的连接
    max-idle: 20    #连接池中最多可空闲maxIdle个连接 ，这里取值为20，表示即使没有数据库连接时依然可以保持20空闲的连接，而不被清除，随时处于待命状态
    max-wait: 15000    #最大阻塞等待时间,单位毫秒