
spring:
  #环境切换
  profiles:
    #生产环境
    active: pro
    #开发环境
    #active: dev

  #数据源
  datasource:
    #jdbc配置
    driverClass: com.mysql.cj.jdbc.Driver #数据库驱动类
    user: root        #数据库用户名
    password: root
    jdbcUrl: jdbc:mysql://localhost:3306/o2o?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC  #数据库连接URL
    #c3cp0连接池
    type: com.mchange.v2.c3p0.ComboPooledDataSource  #指定自定义连接池类型，不指定则默认使用hikari
    dataSourceName: dataSource
    initialPoolSize: 1    #连接池初始化连接数
    minPoolSize: 1        #连接池最小连接数
    maxPoolSize: 20       #连接池最大连接数
    autoCommitOnClose: false  #关闭连接后不自动提交
    checkoutTimeout: 10000    #连接超时时间
    maxIdleTime: 1800000      #连接的最大空闲时间，超过这个时间，某个数据库连接还没有被使用，则会断开掉这个连接
    acquireRetryAttempts: 2   #连接池在获取连接失败后允许重试次数

  #thymeleaf模板配置
  thymeleaf:
    cache: false                   #取消缓存，避免改了模板还要重启服务器，但不配置也没问题
    prefix: classpath:/templates/  #模板文件视图前缀，默认是classpath:/templates/，可不用配置
    suffix: .html                  #模板文件视图后缀，默认是.html，可不用配置
    check-template-location: true  #检查模板位置，这个可以不配置
    encoding: utf-8                #编码字符集，默认是utf-8，可不用配置
    mode: HTML                     #模板的模式，默认是HTML，可不用配置
    servlet:
      content-type: text/html
  #文件上传解析器
  #servlet:
    #multipart:
      #max-file-size: 1Mb       #单个文件上传允许的最大内存
      #max-request-size: 30MB    #所有文件上传允许的最大内存

#Mybatis
mybatis:
  config-location: classpath:config/mybatis.xml      #mybatis全局配置文件路径
  mapper-locations: classpath:mapper/*.xml    #mapper映射文件路径
  type-aliases-package: com.cd.o2o.entity    #实体类别名
  #开启驼峰命名规则（由于我在配置文件中开启了，这里就不额外设置了，注释掉）
  #configuration:
    #map-underscore-to-camel-case: true

#在MyBatis Log日志中打印SQL语句
logging:
  level:
    com.cd.o2o.dao: debug
